### ISSUE TITLE
Blog URL

### ISSUE THREAD

**Issue by BlueArcherX** [jeffgreenca/auto-vester-example#1]
Hi Jeff,  I have seen a lot of your great work in the Vester Repo, and I came across this, but noticed your blog is offline.  Any way at all that you could post the text contents of the blog post for this project on a Wiki page on this repo?  I would really love to learn more about this project!

Great work!

**Comment by jeffgreenca** [comment]
I would encourage you instead to look at PowerCLI DSC extensions to replace Vester - https://blogs.vmware.com/PowerCLI/2018/12/getting-started-dsc-for-vmware.html - in fact, I think I'll add a note to the this repo about that.

That said, waybackmachine remembers all, if you'd like to see the original article - https://web.archive.org/web/20180530203159/https://virtualdatacave.com/
